Remove TA headers that breaks the build
Fixes the following error:
../LibChemist/build_lc_210112/_deps/tiledarray-src/src/TiledArray/math/linalg/scalapack/block_cyclic.h:115:37: error: ‘make_ta_range’ is not a member of ‘TiledArray::detail’
  115 |                 TiledArray::detail::make_ta_range(tile.range()), {i, j},